sonarqube_job:
  stage: test
  script:
    - git config --global user.email "devops@server.w"
    - git config --global user.name "devops"
    - git checkout origin/master
    - git merge --no-commit --no-ff $CI_COMMIT_SHA
    - npm install sonarqube-scanner
    - export SONAR_SCANNER_MIRROR=https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/
    - ./node_modules/sonarqube-scanner/dist/bin/sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD -Dsonar.projectName=alerter_${CI_COMMIT_REF_NAME} -Dsonar.projectKey=alerter_${CI_COMMIT_REF_NAME}
